-- Basic filtering
SELECT NAME
FROM CITY
WHERE COUNTRYCODE = 'USA' 
AND POPULATION > 120000;

-- Duplicate check
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) AS duplicate_cities
FROM STATION;

-- Even ID + distinct
SELECT DISTINCT CITY
FROM STATION
WHERE ID % 2 = 0;

-- Shortest city name
SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY), CITY
LIMIT 1;

-- Longest city name
SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY
LIMIT 1;
